modify yml

diff --git a/.github/workflows/schedule.yml b/.github/workflows/schedule.yml
--- a/.github/workflows/schedule.yml
+++ b/.github/workflows/schedule.yml
@@ -21,7 +21,7 @@ jobs:
     - name: Install Dependencies
       run: |
         python -m pip install --upgrade pip
-        pip install -r requirements.txt
+        pip install -r requirements.txt || { echo 'pip install failed'; exit 1; }
 
     - name: Run Data Producer
       run: python data_producer.py
